---
messages:
  luckyDrawStart: "ğŸ¥ğŸ¥ğŸ¥  æŠ½çæ´»å‹•é–‹å§‹!!! æ¬²åƒåŠ æ­¤æ¬¡æŠ½çæ´»å‹•ï¼Œè«‹åœ¨ {{ .joinDuration }} åˆ†é˜å…§ï¼Œ*å›è¦†* é€™å‰‡è¨Šæ¯æˆ–å›è¦† /joinDraw ğŸ¥ğŸ¥ğŸ¥"
  thereAreNMembersJoined: "ğŸ¥ æœ‰ {{ .numberOfMembers }} ä½æœƒå“¡åƒåŠ æ­¤æ¬¡æŠ½ç! ğŸ‘¯ğŸ‘¯ğŸ‘¯"
  thereIsOneMemberJoined: "ğŸ¥ åªæœ‰ä¸€ä½æœƒå“¡åƒåŠ æ­¤æ¬¡æŠ½ç! ğŸ‘¯ğŸ‘¯ğŸ‘¯"
  noOneJoined: "æ²’æœ‰ä»»ä½•äººåƒåŠ æ­¤æ¬¡æŠ½ç ğŸ¥º"
  timeLeftToJoin: "â± åªå‰© {{ .timeLeft }} åˆ†é˜é–‹å§‹æŠ½ç!"
  willChooseNumberOfPersons: "ğŸ™ æ¥ä¸‹ä¾†çé …æ˜¯ {{ .prize }}ï¼Œæˆ‘æœƒæŠ½å‡º {{ .quantity }} ä½å¹¸é‹è€…~~"
  willChooseOnePerson: "ğŸ™ æ¥ä¸‹ä¾†çé …æ˜¯ {{ .prize }}ï¼Œåªæœ‰ä¸€ä½å¹¸é‹è€…~~ ğŸ¥ğŸ¥ğŸ¥"
  winnerIs: "ğŸ™ ç¬¬ {{ .place_number }} ä½å¾—ä¸»æ˜¯... ğŸ¥ğŸ¥ğŸ¥"
  notifyWinner: "ğŸ… æ­å–œ {{ .winner }} !! ğŸ‰ğŸ‰ğŸ‰ ä½ è´å¾—äº† {{ .prize }}!, è«‹æä¾›ä½ çš„å¸³è™Ÿ E-mail çµ¦ä¸»è¾¦äºº {{- .organizer -}} ~ ğŸ‘ğŸ‘ğŸ‘"
  allMembersGotTheirPrize: "ğŸ… æ‰€æœ‰çš„æœƒå“¡éƒ½å·²ç¶“æŠ½ä¸­çå“ ğŸ‰"
  theDrawIsOver: "*æŠ½çæ´»å‹•å·²ç¶“çµæŸï¼Œè¬è¬å¤§å®¶åƒåŠ æ­¤æ¬¡æŠ½ç~~!!* ğŸ‰ğŸ‰ğŸ‰"
  theDrawIsNotStartedYet: "âœ‹ æŠ½çæ´»å‹•é‚„æ²’é–‹å§‹å–”~"
  theDrawIsAlreadyStartedAndHasNotStoppedYet: "æŠ½çæ´»å‹•å·²ç¶“é–‹å§‹äº†ï¼Œè€Œä¸”é‚„æœªçµæŸ~"
